# ---------- Build Stage ----------
FROM node:22-alpine AS builder

WORKDIR /app

# Copy only package files first
COPY package*.json ./

# Install ALL deps (including dev)
RUN npm install

# Copy rest of the code
COPY . .

# Build (if you have build step — TS etc.)


# ---------- Production Stage ----------
FROM node:22-alpine AS runner

WORKDIR /app

# Copy only required files to production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules


EXPOSE 5500

# Only run the built code
CMD ["node", "dist/index.js"]
