apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://shahiid1309_db_user:C1Na5UCsgDyEkQbX@cluster0.tbsedbm.mongodb.net/studentDB?retryWrites=true&w=majority&appName=Cluster0"





